const $ = (selector) => document.querySelector(selector);
const PLUGIN_ID = "harmony-audit";
const state = { runs: [], selected: null, capabilities: [], profile: null, source: null, readiness: null, models: [], reportRuns: new Set(), executions: [], taskDetail: null, executionTimer: null, token: localStorage.getItem("agent-platform-token") || "" };
const esc = (value) => String(value ?? "").replace(/[&<>"']/g, (char) => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]));
const auth = () => state.token ? { authorization: `Bearer ${state.token}` } : {};
async function api(path, options = {}) { const response = await fetch(path, { ...options, headers: { "content-type":"application/json", ...auth(), ...(options.headers || {}) } }); const value = await response.json(); if (!response.ok) throw new Error(value.error || `HTTP ${response.status}`); return value; }
function toast(text) { const node = $("#toast"); node.textContent = text; node.classList.add("show"); clearTimeout(node.timer); node.timer = setTimeout(() => node.classList.remove("show"), 2800); }
function show(id) { document.querySelectorAll(".view").forEach((view) => view.classList.add("hidden")); $(id).classList.remove("hidden"); }
function detailsOf(run) { return run.snapshot?.details || {}; }
function targetOf(run) { return detailsOf(run).run?.target_repo || "正在初始化…"; }
function statusOf(run) { return detailsOf(run).run?.status || run.status || "preparing"; }
function label(status) { return ({complete:"已完成",complete_with_gaps:"完成·有缺口",running:"运行中",preparing:"准备中",resuming:"恢复中",failed:"失败",cancelled:"已取消"})[status] || status; }
function renderReadiness() { const value=state.readiness,pill=$("#readiness-pill"),detail=$("#readiness-detail"),submit=$(".submit");if(!value){pill.className="live-pill failed";pill.innerHTML="<i></i> 配置检查失败";detail.className="readiness-detail failed";detail.textContent="无法读取插件就绪状态";submit.disabled=true;return}const failed=value.checks.filter((check)=>!check.ok);pill.className=`live-pill ${value.ready?'ready':'failed'}`;pill.innerHTML=`<i></i> ${value.ready?'插件已就绪':'配置未就绪'}`;detail.className=`readiness-detail ${value.ready?'ready':'failed'}`;detail.textContent=value.ready?`Atlas、模型和 Skills 已就绪 · 默认模型 ${value.defaults.model}`:failed.map((check)=>`${check.id}: ${check.message}`).join("；");submit.disabled=!value.ready;if(value.defaults?.capacity)$("#capacity").value=String(value.defaults.capacity);}
function renderModels() { $("#model-options").innerHTML=state.models.map((model)=>`<option value="${esc(model)}"></option>`).join(""); }
function renderRuns() { $("#run-list").innerHTML = state.runs.length ? state.runs.map((run) => {const target=targetOf(run);return `<button class="run-item ${state.selected?.id===run.id?'active':''}" data-run="${esc(run.id)}"><strong>${esc(target.split('/').pop() || target)}</strong><span><em>${esc(label(statusOf(run)))}</em><time>${new Date(run.updatedAt).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</time></span></button>`}).join("") : '<div class="empty compact">尚无运行记录</div>'; document.querySelectorAll("[data-run]").forEach((node) => node.onclick = () => selectRun(node.dataset.run)); }
async function loadRuns() { const value = await api("/api/runs"); state.runs = value.runs.filter((run)=>run.pluginId===PLUGIN_ID); renderRuns(); if (state.selected) { const fresh = state.runs.find((run) => run.id === state.selected.id); if (fresh) { state.selected = fresh; renderDetail(); } } }
function checked(selector) { return [...document.querySelectorAll(selector+':checked')].map((node) => node.value); }
function renderCapabilities() { $("#capability-options").innerHTML = state.capabilities.filter((item)=>item.status==='enabled').map((item)=>`<label class="option"><input type="checkbox" name="capability" value="${esc(item.capability_id)}"><span><strong>${esc(item.title)}</strong><span>${esc(item.domain)}</span></span><code>${esc(item.capability_id)}</code></label>`).join(""); }
function renderProfile(model) { state.profile = model; const summary = model.summary || {}; $("#profile-summary").classList.remove("hidden"); $("#profile-summary").innerHTML = `<strong>${esc(model.application?.bundle_name || '项目解析完成')}</strong>　${summary.modules||model.modules?.length||0} 个模块 · ${summary.components||model.components?.length||0} 个组件 · ${summary.entry_candidates||model.entry_candidates?.length||0} 个入口候选`; $("#component-options").innerHTML = model.components?.length ? model.components.map((item)=>`<label class="option"><input type="checkbox" name="component" value="${esc(item.component_id)}"><span><strong>${esc(item.name || item.component_id)}</strong><span>${esc(item.module_name)} · ${esc(item.kind)}</span></span><code>${item.exported===true?'EXPORTED':''}</code></label>`).join("") : '<div class="empty compact">未发现组件</div>'; if($('#incremental').checked)$('#incremental').onchange(); }
function renderSlots(tasks) { const active = tasks.filter((task)=>task.status==='running'),kind=(value)=>({component_semantic_analysis:'路径发现',exploitability_validation:'六维验证',poc_generation:'PoC 生成'})[value]||value; $("#pool-caption").textContent = active.length ? `${active.length} / 5 个槽位活动` : '当前无活动任务'; $("#slots").innerHTML = Array.from({length:5},(_,i)=>{const task=active[i];return `<div class="slot ${task?'active':''}" ${task?`data-execution="${esc(task.task_id)}"`:''}><b>SLOT ${String(i+1).padStart(2,'0')}</b><i class="pulse"></i>${task?`<strong>${esc(kind(task.kind))}</strong><span>${esc(task.subject_id)} · 尝试 ${esc(task.attempts)}</span>`:'<strong>空闲</strong><span>等待调度</span>'}</div>`}).join(''); document.querySelectorAll('.slot[data-execution]').forEach((node)=>node.onclick=()=>openExecution(node.dataset.execution)); }
const executionLabel=(status)=>({queued:'排队中',running:'运行中',succeeded:'已完成',failed:'失败',cancelled:'已取消'})[status]||status;
function renderExecutions(){const root=$("#execution-list");if(!state.executions.length){root.innerHTML='<div class="empty">暂无子 Agent 任务</div>';return}root.innerHTML=state.executions.map((item)=>`<button class="execution-row" data-task="${esc(item.id)}"><span><strong>${esc(item.title)}</strong><small>${esc(item.id)}</small></span><code>${esc(item.subject||'—')}</code><span class="execution-status ${esc(item.status)}">${esc(executionLabel(item.status))}</span><small>尝试 ${esc(item.attempt)}</small></button>`).join('');root.querySelectorAll('[data-task]').forEach((node)=>node.onclick=()=>openExecution(node.dataset.task));}
async function loadExecutions(){if(!state.selected?.id)return;const value=await api(`/api/runs/${encodeURIComponent(state.selected.id)}/executions`);state.executions=value.executions||[];renderExecutions();}
const json=(value)=>JSON.stringify(value,null,2);
function traceTitle(event){const payload=event.payload||{};return({agent_started:'Agent 开始执行',assistant_message:'模型过程输出',tool_call_started:`调用工具 ${payload.tool||''}`,tool_call_completed:`工具完成 ${payload.tool||''}`,submission_started:'开始提交结构化结果',submission_accepted:'结构化结果已接受',submission_rejected:'结构化结果被拒绝',agent_completed:'Agent 执行完成',agent_failed:'Agent 执行失败',task_completed:'任务结果已入库',task_rejected:'任务尝试被拒绝',task_lease_recovered:'任务租约已恢复'})[event.type]||event.type;}
function traceSummary(event){const payload=event.payload||{};if(event.type==='assistant_message'){const blocks=Array.isArray(payload.content)?payload.content:[];return blocks.map((block)=>block?.text||'').filter(Boolean).join('\n')||payload.errorMessage||''}if(event.type==='tool_call_completed')return payload.isError?'工具返回错误':'工具调用成功';if(event.type==='agent_failed'||event.type==='submission_rejected'||event.type==='task_rejected')return payload.error||payload.status||'';return '';}
function renderExecutionDetail(){const value=state.taskDetail;if(!value)return;const item=value.execution;$("#execution-title").textContent=`${item.title} · ${item.subject||item.id}`;$("#execution-meta").innerHTML=`<span>${esc(executionLabel(item.status))}</span><span>${esc(item.kind)}</span><span>尝试 ${esc(item.attempt)}</span><span>${esc(item.id)}</span>`;$("#execution-input").textContent=json(value.input||{});const attemptMap=new Map((value.attempts||[]).map((attempt)=>[attempt.attempt,attempt]));let current=-1;$("#execution-timeline").innerHTML=(value.events||[]).map((event)=>{let heading='';if(event.attempt!==current){current=event.attempt;const attempt=attemptMap.get(current);heading=`<div class="attempt-heading"><strong>ATTEMPT ${esc(current)}</strong><span>${esc(attempt?executionLabel(attempt.status):'')}</span></div>`}const summary=traceSummary(event),payload=event.payload,hasPayload=payload&&Object.keys(payload).length>0;return `${heading}<article class="trace-event ${esc(event.type)}"><header><b>${esc(traceTitle(event))}</b><time>${esc(new Date(event.timestamp).toLocaleTimeString())}</time></header>${summary?`<p>${esc(summary)}</p>`:''}${hasPayload?`<details><summary>查看事件数据</summary><pre>${esc(json(payload))}</pre></details>`:''}</article>`}).join('')||'<div class="empty">这个任务没有可用的历史轨迹；新版本运行的任务会在这里实时记录。</div>';}
async function openExecution(id){try{state.taskDetail=await api(`/api/runs/${encodeURIComponent(state.selected.id)}/executions/${encodeURIComponent(id)}`);renderExecutionDetail();$("#execution-dialog").showModal()}catch(error){toast(error.message)}}
function scheduleExecutionRefresh(){if(state.executionTimer)return;state.executionTimer=setTimeout(async()=>{state.executionTimer=null;try{await loadExecutions();if(state.taskDetail&&$("#execution-dialog").open){state.taskDetail=await api(`/api/runs/${encodeURIComponent(state.selected.id)}/executions/${encodeURIComponent(state.taskDetail.execution.id)}`);renderExecutionDetail()}}catch{}},300);}
function renderDetail() { const run=state.selected;if(!run)return; const status=statusOf(run),data=detailsOf(run),tasks=data.tasks||[],counts=data.task_counts||{},findings=data.findings||[],gaps=data.coverage_gaps||[],pending=Number(data.pending_validation_groups||0); $("#run-status").textContent=label(status).toUpperCase(); $("#run-status").className=`status-badge ${status}`; $("#run-updated").textContent=`更新于 ${new Date(run.updatedAt).toLocaleString()}`; $("#run-target").textContent=targetOf(run); $("#run-id").textContent=data.run?.run_id||run.id; const total=tasks.length||Object.values(counts).reduce((a,b)=>a+Number(b),0),done=Number(counts.completed||0)+Number(counts.exhausted||0)+Number(counts.cancelled||0); $("#task-progress").textContent=`${done} / ${total}`; $("#progress-bar").style.width=`${total?Math.round(done/total*100):0}%`; $("#finding-count").textContent=findings.length; $("#gap-count").textContent=gaps.length; $("#gap-caption").textContent=pending?`${pending} 个操作组仍待验证`:'需要人工关注'; $("#generation").textContent=data.run?.resume_generation||0; renderSlots(tasks); $("#findings").innerHTML=findings.length?findings.map((item)=>`<tr><td><span class="severity ${esc(item.severity)}">${esc(item.severity||'—')}</span></td><td>${esc(item.title)}</td><td><code>${esc(item.cwe||'—')}</code></td></tr>`).join(''):'<tr><td colspan="3" class="empty">尚无已确认 Finding</td></tr>'; $("#gaps").innerHTML=gaps.length?gaps.map((gap)=>{const details=gap.details||{};return `<div class="gap"><strong>${esc(gap.kind||gap.type||gap.code||'覆盖缺口')}</strong>${esc(details.error||gap.reason||gap.subject_id||JSON.stringify(gap))}</div>`}).join(''):`<div class="empty">${pending?`${pending} 个操作组正在验证，尚未形成最终缺口`:'暂无覆盖缺口'}</div>`; const reportAvailable=state.reportRuns.has(run.id); $("#report-panel").classList.toggle('hidden',!reportAvailable); if(reportAvailable){const url=`/api/runs/${encodeURIComponent(run.id)}/artifacts/report-html${state.token?`?token=${encodeURIComponent(state.token)}`:''}`;$("#open-report").href=url;if($("#report-frame").dataset.run!==run.id){$("#report-frame").src=url;$("#report-frame").dataset.run=run.id}} $("#cancel-run").disabled=!['running','preparing','accepted'].includes(status); $("#resume-run").disabled=!['failed','complete_with_gaps'].includes(status); renderRuns(); }
async function refreshArtifacts(run) { if(!run?.pluginRun)return;try{const value=await api(`/api/runs/${encodeURIComponent(run.id)}/artifacts`);if(value.artifacts.some((artifact)=>artifact.id==='report-html'))state.reportRuns.add(run.id);else state.reportRuns.delete(run.id)}catch{state.reportRuns.delete(run.id)} }
function connectEvents(run) { state.source?.close(); const url=`/api/runs/${encodeURIComponent(run.id)}/events${state.token?`?token=${encodeURIComponent(state.token)}`:''}`; state.source=new EventSource(url); const replace=async(value)=>{state.selected=value.run||value;const index=state.runs.findIndex((item)=>item.id===state.selected.id);if(index>=0)state.runs[index]=state.selected;else if(state.selected.pluginId===PLUGIN_ID)state.runs.unshift(state.selected);await refreshArtifacts(state.selected);renderDetail()}; state.source.addEventListener('snapshot',(event)=>{void replace(JSON.parse(event.data));scheduleExecutionRefresh()}); state.source.addEventListener('host_event',(event)=>{void replace(JSON.parse(event.data));scheduleExecutionRefresh()}); state.source.addEventListener('plugin_event',async(event)=>{try{const pluginEvent=JSON.parse(event.data);if(pluginEvent.type==='agent_trace'){scheduleExecutionRefresh();return}await replace(await api(`/api/runs/${encodeURIComponent(run.id)}`));scheduleExecutionRefresh()}catch(error){toast(error.message)}}); }
async function selectRun(id) { try{state.selected=await api(`/api/runs/${encodeURIComponent(id)}`);await Promise.all([refreshArtifacts(state.selected),loadExecutions()]);show('#run-view');$('#page-title').textContent='运行详情';renderDetail();connectEvents(state.selected)}catch(error){toast(error.message)} }
function openDialog(title, html, confirm) { $('#dialog-title').textContent=title;$('#dialog-body').innerHTML=html;const dialog=$('#simple-dialog');$('#dialog-confirm').onclick=(event)=>{event.preventDefault();confirm(dialog);};dialog.showModal(); }
$('#new-run').onclick=$('#hero-new-run').onclick=()=>{show('#create-view');$('#page-title').textContent='新建审计'};document.querySelectorAll('.close-view').forEach((node)=>node.onclick=()=>{show('#welcome-view');$('#page-title').textContent='审计工作台'});$('#refresh').onclick=()=>loadRuns().catch((error)=>toast(error.message));
$('#profile-project').onclick=async()=>{try{$('#profile-project').textContent='解析中…';renderProfile(await api(`/api/plugins/${PLUGIN_ID}/operations/profile`,{method:'POST',body:JSON.stringify({target:$('#target').value})}));toast('项目模型解析完成')}catch(error){toast(error.message)}finally{$('#profile-project').textContent='解析项目'}};
$('#incremental').onchange=()=>{const enabled=$('#incremental').checked;document.querySelectorAll('[name=component],[name=capability]').forEach((node)=>{node.disabled=enabled;if(enabled)node.checked=false});document.querySelector('.scope-options').classList.toggle('disabled',enabled)};
$('#audit-form').onsubmit=async(event)=>{event.preventDefault();try{const payload={target:$('#target').value,incremental:$('#incremental').checked,components:checked('[name=component]'),capabilities:checked('[name=capability]'),capacity:Number($('#capacity').value),model:$('#model').value||undefined};const run=await api('/api/runs',{method:'POST',body:JSON.stringify({pluginId:PLUGIN_ID,payload})});state.runs.unshift(run);await selectRun(run.id);toast(payload.incremental?'增量审计任务已创建':'审计任务已创建')}catch(error){toast(error.message)}};
$('#cancel-run').onclick=async()=>{if(!confirm('确认取消当前审计？已运行的模型调用可能需要片刻退出。'))return;try{state.selected=await api(`/api/runs/${encodeURIComponent(state.selected.id)}/actions/cancel`,{method:'POST',body:'{}'});renderDetail()}catch(error){toast(error.message)}};
$('#resume-run').onclick=async()=>{try{state.selected=await api(`/api/runs/${encodeURIComponent(state.selected.id)}/actions/resume`,{method:'POST',body:JSON.stringify({capacity:5})});renderDetail();connectEvents(state.selected)}catch(error){toast(error.message)}};
$('#rebuild-report').onclick=async()=>{try{state.selected=await api(`/api/runs/${encodeURIComponent(state.selected.id)}/actions/rebuild-report`,{method:'POST',body:'{}'});await refreshArtifacts(state.selected);renderDetail();toast('报告已重建')}catch(error){toast(error.message)}};
$('#settings').onclick=()=>openDialog('访问设置',`<label class="field"><span>Web API Token</span><input id="token-input" type="password" value="${esc(state.token)}" placeholder="服务未启用 Token 时留空"><small>仅保存在当前浏览器。</small></label>`,(dialog)=>{state.token=$('#token-input').value;localStorage.setItem('agent-platform-token',state.token);dialog.close();location.reload()});
$('#adopt-run').onclick=()=>openDialog('导入已有 Run',`<label class="field"><span>Run Directory 绝对路径</span><input id="adopt-path" placeholder="/path/to/reports/harmony-audit-RUN..."></label>`,async(dialog)=>{try{const run=await api('/api/runs/adopt',{method:'POST',body:JSON.stringify({pluginId:PLUGIN_ID,pluginRun:{id:$('#adopt-path').value}})});dialog.close();await loadRuns();await selectRun(run.id)}catch(error){toast(error.message)}});
async function boot(){try{await api('/api/health');$('#health-dot').classList.add('ok');$('#health-text').textContent='服务运行正常';const [value,assistant]=await Promise.all([api(`/api/plugins/${PLUGIN_ID}/operations/capabilities`,{method:'POST',body:'{}'}),api('/api/assistant')]);state.capabilities=value.capabilities;state.models=assistant.models||[];renderCapabilities();renderModels();try{state.readiness=await api(`/api/plugins/${PLUGIN_ID}/operations/readiness`,{method:'POST',body:'{}'})}catch(error){state.readiness={ready:false,checks:[{id:'plugin',ok:false,message:error.message}],defaults:{capacity:5,model:'unavailable'}}}renderReadiness();await loadRuns()}catch(error){$('#health-text').textContent='服务连接失败';toast(error.message)}}boot();
