export type InvariantErrorCode =
  | "TASK_NOT_RUNNING" | "STALE_TASK_ATTEMPT" | "TASK_ID_MISMATCH" | "ENTRY_ID_MISMATCH"
  | "DUPLICATE_LOCAL_ID" | "UNKNOWN_EVIDENCE_REF" | "EVIDENCE_OUTSIDE_OPERATION_GROUP"
  | "HYPOTHESIS_EVIDENCE_NOT_ADMISSIBLE" | "SYMBOL_REF_EVIDENCE_MISSING" | "INVALID_FACT_EDGE"
  | "CONFIRMED_ENTRY_SYMBOL_MISSING" | "EXCLUDED_ENTRY_HAS_OUTPUTS" | "EXCLUDED_ENTRY_HAS_EXTERNAL_ENTRY"
  | "CONFIRMED_EXTERNAL_ENTRY_REQUIRES_COMPONENT_INPUT" | "CONFIRMED_EXTERNAL_ENTRY_CANDIDATE_MISSING"
  | "UNCONFIRMED_EXTERNAL_ENTRY_HAS_CANDIDATES" | "NO_EXTERNAL_CANDIDATE_REQUIRES_EXCLUDED_STATUS"
  | "UNKNOWN_CONFIRMED_EXTERNAL_CANDIDATE"
  | "CAPABILITY_OUT_OF_SCOPE" | "CAPABILITY_NOT_ENABLED" | "CAPABILITY_CATEGORY_MISMATCH"
  | "UNKNOWN_TARGET_COMPONENT" | "INVALID_PARAMETER_MAPPING" | "INVALID_INVOCATION_CONTROL" | "MISSING_GROUP_VALIDATION"
  | "UNEXPECTED_GROUP_VALIDATION" | "DUPLICATE_GROUP_VALIDATION" | "CONFIRMED_DIMENSIONS_INCOMPLETE"
  | "CONFIRMED_DETAILS_INCOMPLETE" | "DEMOTION_REASON_MISSING" | "EVIDENCE_GAP_MISSING"
  | "DOS_SEMANTIC_MISMATCH" | "PRINCIPAL_CHAIN_INCOMPLETE" | "CONFIRMED_ENTRY_REQUIRED"
  | "HYPOTHESIS_BASIS_MISSING" | "DIRECT_EFFECT_EVIDENCE_MISSING" | "TRUE_DIMENSION_EVIDENCE_INSUFFICIENT"
  | "FALSE_DIMENSION_EVIDENCE_INSUFFICIENT" | "SECURITY_CHECK_OUTCOME_DIMENSION_MISMATCH"
  | "CLASSIFICATION_DECISION_MISMATCH"
  | "CONFIRMED_EFFECT_CHAIN_INCOMPLETE" | "CONFIRMED_EFFECT_NOT_INDEPENDENTLY_VERIFIED"
  | "IDENTITY_COLLISION" | "UNSUPPORTED_SCHEMA_VERSION" | "ILLEGAL_STATE_TRANSITION" | "SCHEMA_INVALID"
  | "FINDING_ID_MISMATCH" | "POC_ENTRY_TYPE_MISMATCH" | "POC_CODE_REQUIRED" | "POC_EXPECTED_OBSERVATION_REQUIRED"
  | "POC_TRIGGER_KIND_REQUIRED" | "POC_TRIGGER_PAYLOAD_REQUIRED" | "POC_TRIGGER_PAYLOAD_EMPTY"
  | "POC_PLACEHOLDER_FOUND" | "POC_FORBIDDEN_OUTPUT" | "POC_SHELL_COMMAND_REQUIRED" | "POC_SHELL_TRIGGER_MISMATCH"
  | "POC_ARKTS_TRIGGER_MISMATCH" | "POC_ARKTS_API_REQUIRED";

export class AuditInvariantError extends Error {
  constructor(readonly code: InvariantErrorCode, readonly details?: unknown) {
    super(`${code}${details === undefined ? "" : `:${JSON.stringify(details)}`}`);
    this.name = "AuditInvariantError";
  }
}

export function invariant(condition: unknown, code: InvariantErrorCode, details?: unknown): asserts condition {
  if (!condition) throw new AuditInvariantError(code, details);
}
